<?php
    $sugar_config_si = array (
    'setup_db_host_name' => 'localhost',
    'setup_db_database_name' => 'sugarcrm',
    'setup_db_drop_tables' => 0,
    'setup_db_create_database' => 1,
    'setup_site_admin_user_name' => 'admin',
    'setup_site_admin_password' => 'dmb4136',
    'setup_db_create_sugarsales_user' => 0,
    'setup_db_admin_user_name' => 'root',
    'setup_db_admin_password' => 'dmb4136',
    'setup_license_key_users' => 1,
    'setup_license_key_expire_date' => '2010-12-12',
    'setup_license_key_oc_licences' => 0,
    'setup_license_key' => 'sugar',
    'setup_site_url' => 'http://127.0.0.1:8080/sugarcrm',
    'dbUSRData' => '***unknown variable dbusrdata***',
    'setup_db_sugarsales_user' => '***unknown variable setup_db_sugarsales_user***',
    'setup_db_sugarsales_password' => '***unknown variable setup_db_sugarsales_password***',
    'setup_db_type' => 'mysql',
    'setup_system_name' => '127.0.0.1',
    'default_currency_iso4217' => 'USD',
    'default_currency_name' => 'US Dollars',
    'default_currency_significant_digits' => '2',
    //'default_currency_symbol' => '$',
    'default_date_format' => 'm/d/Y',
    'default_time_format' => 'h:ia',
    'default_decimal_seperator' => '.',
    'default_export_charset' => 'ISO-8859-1',
    'default_language' => 'en_us',
    'default_locale_name_format' => 's f l',
    'default_number_grouping_seperator' => ',',
    'export_delimiter' => ',',
    'demoData' => 'yes',
    'setup_site_sugarbeet_anonymous_stats' => '0',
    'setup_site_sugarbeet_automatic_checks' => '0',
    'setup_site_specify_guid' => '0',
    'setup_site_guid' => '',
    );
    ?> 
            